from src.constants.paths import STATS_DATA_DIR_PATH

BARH_MAX_WORDS_COUNT = 20
CLOUD_MAX_WORDS_COUNT = 100

STATS_CHARTS_DIR_PATH = f'{STATS_DATA_DIR_PATH}/charts'

UGTF_CLOUD_FILE = f'{STATS_CHARTS_DIR_PATH}/ugtf_cloud.jpg'
UGIDF_CLOUD_FILE = f'{STATS_CHARTS_DIR_PATH}/ugidf_cloud.jpg'
UGTF_BARH_FILE = f'{STATS_CHARTS_DIR_PATH}/ugtf_barh.jpg'
UGIDF_BARH_FILE = f'{STATS_CHARTS_DIR_PATH}/ugidf_barh.jpg'
BGTF_BARH_FILE = f'{STATS_CHARTS_DIR_PATH}/bgtf_barh.jpg'
BGIDF_BARH_FILE = f'{STATS_CHARTS_DIR_PATH}/bgidf_barh.jpg'
