DATA_DIR_PATH = '../data'
RTF_DATA_DIR_PATH = f'{DATA_DIR_PATH}/rtf'
TXT_DATA_DIR_PATH = f'{DATA_DIR_PATH}/txt'
ANALYSIS_DATA_DIR_PATH = f'{DATA_DIR_PATH}/analysis'

STATS_DATA_DIR_PATH = f'{DATA_DIR_PATH}/stats'
STATS_PAIRS_DATA_DIR_PATH = f'{STATS_DATA_DIR_PATH}/pairs'
STATS_COMMON_DATA_DIR_PATH = f'{STATS_DATA_DIR_PATH}/common.txt'

EFF_DATA_DIR_PATH = f'{DATA_DIR_PATH}/eff'
EFF_ITER_1_DATA_DIR_PATH = f'{EFF_DATA_DIR_PATH}/eff_1'
EFF_CONC_ITER_1_DATA_DIR_PATH = f'{EFF_DATA_DIR_PATH}/conclusion_1.json'
EFF_ITER_2_DATA_DIR_PATH = f'{EFF_DATA_DIR_PATH}/eff_2'
EFF_CONC_ITER_2_DATA_DIR_PATH = f'{EFF_DATA_DIR_PATH}/conclusion_2.json'

INSIGHTS_DATA_DIR_PATH = f'{DATA_DIR_PATH}/insights'
